name: Train rf weather model
description: train a random forest model with default parameters
inputs:
- {name: feature_data_path, type: String}
- {name: rf_weather_model_path, type: String}
- {name: validation_days, type: Integer}
outputs:
- {name: Output, type: String}
implementation:
  container:
    image: python:3.7
    command:
    - sh
    - -c
    - (PIP_DISABLE_PIP_VERSION_CHECK=1 python3 -m pip install --quiet --no-warn-script-location
      'scikit-learn' 'fastparquet' 'fsspec' 'gcsfs' 'google-cloud-storage' || PIP_DISABLE_PIP_VERSION_CHECK=1
      python3 -m pip install --quiet --no-warn-script-location 'scikit-learn' 'fastparquet'
      'fsspec' 'gcsfs' 'google-cloud-storage' --user) && "$0" "$@"
    - python3
    - -u
    - -c
    - "def train_rf_weather_model(feature_data_path, rf_weather_model_path, validation_days):\n\
      \    '''train a random forest model with default parameters'''\n    import json\n\
      \    import pandas as pd\n    import _pickle as cPickle # save ML model\n  \
      \  from google.cloud import storage # save the model to GCS\n    from sklearn.ensemble\
      \ import RandomForestRegressor\n    from sklearn.metrics import mean_absolute_error,\
      \ mean_squared_error\n    from sklearn.model_selection import train_test_split\n\
      \    from urllib.parse import urlparse\n\n    # read dataframe\n    weather_df\
      \ = pd.read_parquet(feature_data_path)\n    # holdout latest datelines used\
      \ for validation\n    weather_features_df = weather_df.drop(weather_df.tail(validation_days).index,\
      \ inplace=False, axis=0)\n    # get x and y\n    x_train, y_train = weather_features_df.drop('TG_future',\
      \ axis=1), weather_features_df['TG_future']\n    # split the data for initial\
      \ testing\n    X_train, X_test, Y_train, Y_test = train_test_split(x_train,\
      \ y_train, test_size=0.2,random_state=1)\n\n    # train the model\n    print('Training\
      \ random forest model')\n    print('Shape of X: %s, %s' % (len(x_train), len(x_train.columns)))\n\
      \    model_rf = RandomForestRegressor(random_state = 42, max_depth = 3, min_samples_split\
      \ = 0.1)\n\n    model_rf.fit(X_train, Y_train)\n\n    # some initial testing\n\
      \    predictions = model_rf.predict(X_test)\n    print('mean absolute error\
      \ without optimization: %s' % mean_absolute_error(Y_test, predictions))\n  \
      \  print('mean squared error without optimization is: %s' % mean_squared_error(Y_test,\
      \ predictions)) \n\n    temp_model_path = '/tmp/model.pickle'\n\n    # write\
      \ out output\n    # save the model into temp\n    with open(temp_model_path,\
      \ 'wb') as f:\n        cPickle.dump(model_rf, f, -1)\n\n    # get client and\
      \ write to GCS\n    # parse model write path for GS\n    parse = urlparse(url=rf_weather_model_path,\
      \ allow_fragments=False)\n\n    if parse.path[0] =='/':\n        model_path\
      \ = parse.path[1:]\n    client = storage.Client()\n    bucket = client.get_bucket(parse.netloc)\n\
      \    model = bucket.blob(model_path)\n    model.upload_from_filename(temp_model_path)\n\
      \n    return rf_weather_model_path\n\ndef _serialize_str(str_value: str) ->\
      \ str:\n    if not isinstance(str_value, str):\n        raise TypeError('Value\
      \ \"{}\" has type \"{}\" instead of str.'.format(str(str_value), str(type(str_value))))\n\
      \    return str_value\n\nimport argparse\n_parser = argparse.ArgumentParser(prog='Train\
      \ rf weather model', description='train a random forest model with default parameters')\n\
      _parser.add_argument(\"--feature-data-path\", dest=\"feature_data_path\", type=str,\
      \ required=True, default=argparse.SUPPRESS)\n_parser.add_argument(\"--rf-weather-model-path\"\
      , dest=\"rf_weather_model_path\", type=str, required=True, default=argparse.SUPPRESS)\n\
      _parser.add_argument(\"--validation-days\", dest=\"validation_days\", type=int,\
      \ required=True, default=argparse.SUPPRESS)\n_parser.add_argument(\"----output-paths\"\
      , dest=\"_output_paths\", type=str, nargs=1)\n_parsed_args = vars(_parser.parse_args())\n\
      _output_files = _parsed_args.pop(\"_output_paths\", [])\n\n_outputs = train_rf_weather_model(**_parsed_args)\n\
      \n_outputs = [_outputs]\n\n_output_serializers = [\n    _serialize_str,\n\n\
      ]\n\nimport os\nfor idx, output_file in enumerate(_output_files):\n    try:\n\
      \        os.makedirs(os.path.dirname(output_file))\n    except OSError:\n  \
      \      pass\n    with open(output_file, 'w') as f:\n        f.write(_output_serializers[idx](_outputs[idx]))\n"
    args:
    - --feature-data-path
    - {inputValue: feature_data_path}
    - --rf-weather-model-path
    - {inputValue: rf_weather_model_path}
    - --validation-days
    - {inputValue: validation_days}
    - '----output-paths'
    - {outputPath: Output}
